# Puerto donde corre la app
server.port=8080

# Nombre de la app
spring.application.name=reserva-restauranter

# Configuración H2
spring.datasource.url=jdbc:h2:mem:reservas_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate crea las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Muestra el SQL que ejecuta Hibernate en la consola
spring.jpa.show-sql=true

# Habilita la consola web de H2
spring.h2.console.enabled=true